from django.conf.urls.defaults import *

urlpatterns = patterns('workflow',
    url(r'^$',                                                                          'views.index',                                      name='workflowinstance'),
    url(r'^new/$',                                                                      'views.new_workflow',                               name='workflow-new'),
    url(r'^list/$',                                                                     'views.workflow_listing',                           name='workflow-listing'),
    url(r'^show/(?P<workflow_id>\d+)/(?P<which_display>\w+)/$',                         'views.show_workflow',                              name='workflow-show'),
    url(r'^delete/(?P<workflowinstance_id>\d+)/$',                                      'views.delete_workflow',                            name='workflow-delete'),
    url(r'^category/take/(?P<category_id>\d+)/$',                                       'views.take_category',                              name='take-category'),
    url(r'^category/untake/(?P<category_id>\d+)/$',                                     'views.untake_category',                            name='untake-category'),
    url(r'^item/take/(?P<item_id>\d+)/$',                                               'views.take_item',                                  name='take-item'),
    url(r'^item/untake/(?P<item_id>\d+)/$',                                             'views.untake_item',                                name='untake-item'),
    url(r'^item/validate/(?P<item_id>\d+)/(?P<validation_label>\w+)/$',                 'views.validate_item',                              name='validate-item'),
    url(r'^item/no_state/(?P<item_id>\d+)/$',                                           'views.reset_item_state',                           name='reset-item-state'),
    url(r'^item/show/(?P<item_id>\d+)/$',                                               'views.show_item',                                  name='show-item'),
    url(r'^item/new/$',                                                                 'views.new_item',                                   name='new-item'),
    url(r'^check/(?P<item_id>\d+)/(?P<category_id>\d+)/(?P<workflowinstance_id>\d+)/$', 'views.check_states_before_change',                 name='check-state-before-change'),
    url(r'^changedetails/(?P<item_id>\d+)/$',                                           'views.item_details',                               name='item-details'),
    url(r'^addcomment/(?P<item_id>\d+)/$',                                              'views.item_comments',                              name='item-comments'),
    url(r'^getall/(?P<workflow_id>\d+)/$',                                              'views.get_all_items',                              name='get-all-items'),
    url(r'^set_categories_order/(?P<workflow_id>\d+)/$',                                'views.set_workflow_categories_order',              name='set-categories-order'),
)
