#!/bin/sh
# PostRm script for WebEngine.

set -e

#DEBHELPER#

if [ "$1" = 'remove' ]
then
    sjconf --disable-plugin webengine-workflowinstance || true
    sjconf --uninstall-plugin webengine-workflowinstance || true
    if [ -e /etc/webengine/sjconf/templates/webengine-workflowinstance/webengine-workflowinstance.conf ]
    then
        sjconf --uninstall-template webengine-workflowinstance || true
    fi
    sjconf --uninstall-conf webengine-workflowinstance || true
fi

exit 0
